apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tiya
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0091-tenant/ci10t-777-0091-app/devfile-sample-tiya@sha256:b5abb0f1008c4e740c9e74b30c90c8b6dfa2147b5bfcbdcc3fa1710cd719d314
        name: my-nodejs
        resources: {}
status: {}
